version: '3.8'

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo/data:/data/db
  #     - ./mongo/conf/init_db.js:/docker-entrypoint-initdb.d/init_db.js:ro
  # environment:
  #   MONGO_INITDB_ROOT_USERNAME: root
  #   MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   # environment:
  #   #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #   #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   #   ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   depends_on:
  #     - mongo

  auth:
    image: cesanta/docker_auth
    command: --v=2 --alsologtostderr /config/auth_config.yml
    ports:
      - "5001:5001"
    volumes:
      - ./ssl:/ssl
      - ./cesanta/cesanta_config:/config
      - ./cesanta/cesanta_logs:/logs
    depends_on:
      - mongo
      - registry

  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
    volumes:
      - ./ssl:/certs
      - ./registry/registry_data:/var/lib/registry
      - ./registry/registry_config.yml:/etc/docker/registry/config.yml
