# Implementación MongoDB, revisar reference.yml para más detalles.
#
# Recordar añadir esta configuración al archivo de configuración de Registry.
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "auth_service"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/ssl/certificate.pem"
  key: "/ssl/key.pem"

token:
  issuer: "auth_service" # Debe ser el mismo que el issuer en el archivo de configuración de Registry.
  expiration: 900

mongo_auth:
  dial_info:
    addrs: ["mongo:27017"]
    timeout: "10s"
    database: "registry"
    username: "root"
    password_file: "/config/password.txt"
    enable_tls: false
  collection: "users"

acl_mongo:
  dial_info:
    addrs: ["mongo:27017"]
    timeout: "10s"
    database: "registry"
    username: "root"
    password_file: "/config/password.txt"
    enable_tls: false
  collection: "acl"
  cache_ttl: "30s"

#
# Simple example of a user and ACL configuration.
#

# users:
#   # Password is specified as a BCrypt hash. Use `htpasswd -nB USERNAME` to generate.
#   "admin":
#     password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC" # badmin
#   "test":
#     password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya" # 123

# acl:
#   - match: { account: "admin" }
#     actions: ["*"]
#     comment: "Admin has full access to everything."
#   - match: { account: "test" }
#     actions: ["pull"]
#     comment: 'User "test" can pull stuff.'
